---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: demo
  namespace: monitoring
spec:
  version: v0.22.2
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-demo
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: smtp.gmail.com:587
      smtp_from: email@mail.com
      smtp_auth_username: email@mail.com
      smtp_auth_identity: email@mail.com
      smtp_auth_password: password
      smtp_require_tls: true
    route:
      group_by:
      - cluster
      - alertname
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: email
      routes:
      - receiver: email
        match:
          severity: warning
    receivers:
      - name: email
        email_configs:
        - to: email@mail.com
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'wechat-example'
  receivers:
  - name: 'wechat-example'
    wechatConfigs:
    - apiURL: 'http://wechatserver:8080/'
      corpID: 'wechat-corpid'
      apiSecret:
        name: 'wechat-config'
        key: 'apiSecret'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: wechat-config
data:
  apiSecret: d2VjaGF0LXNlY3JldAo=

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-main
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: demo

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    team: devops-bootcamp
spec:
  endpoints:
  - interval: 15s
    port: web
    scrapeTimeout: 15s
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      operated-alertmanager: "true"
